resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/rattrapdev-public/ConcourseTest.git
    branch: master

jobs:
  - name: build-app
    plan: #Series of steps that make up a pipeline
    - get: source-code #Step that retrieves resources
      trigger: true
    - task: dotnet-build # Executes the configured tasks
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: mcr.microsoft.com/dotnet/core/sdk
            tag: 3.1
        inputs:
        - name: source-code
        run:
            path: sh
            args:
            - -exec
            - |
              dotnet build ./source-code/NetCoreRefresher.sln
    - task: dotnet-test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: mcr.microsoft.com/dotnet/core/sdk
            tag: 3.1
        inputs:
        - name: source-code
        outputs:
        - name: test-results
        run:
          path: sh
          args:
          - -exec
          - |
            dotnet test ./source-code/NetCoreRefresher.sln --logger "trx" --results-directory ../test-results

#ToDo: Move tasks to aliases
#ToDo: Move a task to file
#ToDo: Change dotnet-test tasks to only run unit tests
#ToDo: Containerize default sql server database
#ToDo: Add task for integration tests
#ToDo: Add task for web tests
#ToDo: Move git information and test projects to a separate file
#ToDo: Read git information from file and write to alias. Merge alias to resource step.
#ToDo: Create pull request build based on hyvee pipelines.
#ToDo: Write build results to git and fail/pass build
#ToDo: Create second app with api that can be deployed in container.

#End Goals:
#Best way to run build locally
#Integration test against a deployed database or second app

#Fly drop a pipeline