version: '3'

services:
  db:
    image: postgres:12.4
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=NetcoreRefresh
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1
      - POSTGRES_PORT=6432

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local